apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  labels:
    external-secrets.io/component: controller
  name: sshs.generators.external-secrets.io
spec:
  group: generators.external-secrets.io
  names:
    categories:
    - external-secrets
    - external-secrets-generators
    kind: SSH
    listKind: SSHList
    plural: sshs
    singular: ssh
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          SSH generates a random ssh based on the
          configuration parameters in spec.
          You can specify the length, characterset and other attributes.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SSHSpec controls the behavior of the password generator.
            properties:
              keyType:
                default: RSA
                description: |-
                  KeyType specifies the SSH key type to be generated.
                  Currently only RSA is supported.
                enum:
                - RSA
                type: string
              rsaConfig:
                description: RSAConfig specifies the configuration of the RSA key
                  to be generated.
                properties:
                  bits:
                    default: 4096
                    description: |-
                      Bit size of the RSA Key to be generated.
                      Defaults to 4096
                    type: integer
                required:
                - bits
                type: object
            type: object
          status:
            properties:
              output:
                x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
