{{- if and .Values.webhook.create .Values.webhook.rbac.create (not .Values.webhook.certManager.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "external-secrets.fullname" . }}-webhook
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - "workflows.external-secrets.io"
    - "external-secrets.io"
    - "generators.external-secrets.io"
    resources:
    - "*"
    verbs:
    - "get"
    - "watch"
    - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "external-secrets.fullname" . }}-webhook
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "external-secrets.fullname" . }}-webhook
subjects:
  - name: {{ include "external-secrets-webhook.serviceAccountName" . }}
    namespace: {{ template "external-secrets.namespace" . }}
    kind: ServiceAccount
{{- end }}
