apiVersion: v2
name: external-secrets
description: External secrets management for Kubernetes
type: application
<<<<<<< HEAD
version: 1.6.0
appVersion: v1.6.0
=======
version: "0.18.0"
appVersion: "v0.18.0"
>>>>>>> upstream/main
kubeVersion: ">= 1.19.0-0"
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
maintainers:
  - name: mcavoyk
    email: kellinmcavoy@gmail.com
dependencies:
  - name: spire-crds
    version: 0.5.0
    repository: https://spiffe.github.io/helm-charts-hardened
    condition: spire-crds.enabled
  - name: spire
    version: 0.25.0
    repository: https://spiffe.github.io/helm-charts-hardened
    condition: spire.enabled
  - name: esi-pod-webhook
    version: 0.4.2
    repository: oci://us-central1-docker.pkg.dev/external-secrets-inc-registry/public/charts
    condition: esi-pod-webhook.enabled
  - name: bitwarden-sdk-server
    version: v0.4.2
    repository: oci://ghcr.io/external-secrets/charts
    condition: bitwarden-sdk-server.enabled
