name: "Update Upstream"
on:
  schedule:
    # Everyday, 3AM UTC
    - cron: "0 3 * * *"

  workflow_dispatch:
    inputs: {}


permissions:
  contents: read

jobs:
  update-upstream:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for Git to create PR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main"]
    steps:
    - name: Setup Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: "1.24"

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ matrix.branch }}
        fetch-depth: 0
    - name: create pull request
      run: |
        git config --global user.name "External Secrets Inc Bot"
        git config --global user.email "bot@externalsecrets.com"
        bash hack/update_upstream.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
