name: "Update Upstream"
on:
  schedule:
    # Everyday, 3AM UTC
    - cron: "0 3 * * *"

  workflow_dispatch:
    inputs: {}


permissions:
  contents: read

jobs:
  update-upstream:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for Git to create PR
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main"]
    steps:
    - name: Setup Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: "1.24"
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ matrix.branch }}
        fetch-depth: 0
    - name: login to github app
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.ESI_BOT_APP_ID }}
        private-key: ${{ secrets.ESI_BOT_PRIVATE_KEY }}
    - name: create pull request
      run: |
        git config --global user.name "External Secrets Inc Bot"
        git config --global user.email "bot@externalsecrets.com"
        git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}
        git remote add upstream https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/external-secrets/external-secrets
        git remote set-url upstream --push DISABLE
        git fetch upstream
        git fetch origin
        git checkout origin/main
        git checkout -b update-upstream-$(date +%s)
        git merge upstream/main --no-ff --no-commit || true
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "nothing changed. skipping."
          exit 0;
        fi
        git add .
        git reset HEAD .github
        git checkout .github
        git commit -s -m "chore: update from upstream"
        git push origin update-upstream-$(date +%s)
        gh pr create --title "chore: update from upstream" --body "update upstream" --base main --head update-upstream-$(date +%s)

      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
